### ISSUE TITLE
Undefined function or variable 'ml_ls'

### ISSUE THREAD

**Issue by WGierke** [CellProfiling/FeatureExtraction#2]
Hi there,
I'm trying to run the example script by
`/usr/local/bin/matlab -nodisplay -nodesktop -nosplash -r "masterProductionFeatures('In','Out');"`
but I'm getting the error
```bash
Undefined function or variable 'ml_ls'.

Error in recursiveRunImages (line 46)
listdirs = ml_ls(inpath);

Error in masterProductionFeatures (line 40)
recursiveRunImages(submitstruct,dirpatterns,imgtype)
```
I'm using R2016a. Thanks a lot!

**Comment by devsullivan** [comment]
Hi, 

ml_ls is in the helperfuncs folder. This error is probably because you have not added that folder to your path. 

If you add an addpath command to your command it should work. 
`/usr/local/bin/matlab -nodisplay -nodesktop -nosplash -r "addpath(genpath('/path/to/repo/FeatureExtraction/')); masterProductionFeatures('In','Out');"
`

**Comment by WGierke** [comment]
Thank you, it works now! :)
